### PR TITLE
Feature - Added a demo with a different dataset (Disease & Healthcare Data)

### PR DESCRIPTION
**Pull request by Devanshu-17**
Hey @iamleonie ,

As discussed earlier, I have created a new demo for this project using a different dataset.

I have used Disease dataset which consists of two columns - Disease and their description, similar to the Wine dataset.

Here is the dataset that I used: [Disease Symptom Description Dataset](https://www.kaggle.com/datasets/itachi9604/disease-symptom-description-dataset?select=symptom_Description.csv)

### CODE REVIEW

**Comment by iamleonie** [comment]
Hi @Devanshu-17, thank you for your contribution. Reviews will take a few days at the moment. Thank you for your patience.

**Comment by iamleonie** [comment]
Hi @Devanshu-17, 
Thank you for your contribution. It looks great.
I have created a new repository for your PR, so we don't overwrite the existing demo.
Could you please open a new PR for this repo and we can merge it there.: https://github.com/weaviate-tutorials/DEMO-text-search-diseases

Please let me know if you have any questions.

**Comment by Devanshu-17** [comment]
Hey @iamleonie,

I would love to create a pull request for this repo "https://github.com/weaviate-tutorials/DEMO-text-search-diseases", but I don't believe Github allows us to fork an empty repository. Can you please make an initial commit? Just an empty README.md or License will do.

**Comment by iamleonie** [comment]
Hi @Devanshu-17,
Thanks for letting me know. I have added an empty README.md just now. Please let me know if you run into any other issues.

**Comment by Devanshu-17** [comment]
Hey @iamleonie,

I have opened a pull request in that repository. 😊

**Comment by iamleonie** [comment]
Replaced by https://github.com/weaviate-tutorials/DEMO-text-search-diseases/pull/1

**Comment by iamleonie** [comment]
Related to https://github.com/weaviate-tutorials/DEMO-text-search-wines/issues/1

**Pull request closed without merging**
